### ISSUE TITLE
Angular bin

### ISSUE THREAD

**Issue by Akahadaka** [christianalfoni/webpack-bin#229]
Anyone have a working Angular 2 version on the new version?

I tried, but not very hard. Says "Unable to update sandbox". What am I missing?
https://www.webpackbin.com/bins/-Kf3BwXFfOl8w6OySJi0

(Are subdirectories supported? e.g. filename `app/app.module.ts`)

**Comment by christianalfoni** [comment]
Hi @Akahadaka , I tried making Angular 2 work, but for some reason the "reflect meta data" thingy does not work. The error on your bin is related to using `/` in filename. I have written down to make a fix for that :)

But yeah... I though ts-loader needed an "expose reflect meta data" option, which it has, but for some reason the error remains.

Please have a go at it if you want to, just not use `/` until I have deployed fix :)

**Comment by Akahadaka** [comment]
@christianalfoni Thanks for taking a look. 

I've made a newer, more conservative one somewhat based off an old boilerplate. Still don't seem to have all the settings right? And still getting a near instant "Unable to update sandbox" on save.

This attempt: https://www.webpackbin.com/bins/-Kf3jpS_tFEKeG2tD10l

**Comment by christianalfoni** [comment]
@Akahadaka Okay, so I got it running,

https://www.webpackbin.com/bins/-Kf7FL3lvenQu4JKrVM9

I had to change how the DLL service figures out how to bundle things. It is really hard to do cause there are no package.json rules for defining paths to prebundled versions of the package, source code etc. And packages actually completely contradict each other in how property names in package.json is used.

Anyways... it works :) Also checked your latest bin, it now runs as expected! If it does not it is probably some caching issue, let me know!

**Comment by flexicious** [comment]
The above link is not working for me - it says "Unable to update sandbox" - Even if I start with a simple React bin, its not working - I see an "Internal Server Error" in the Chrome inspector tab, in case that helps.

**Comment by christianalfoni** [comment]
@flexicious That sounds weird. Have you turned off cookies or something? Webpackbin depends on cookies to identify you.

Also if you have time this happens, I can check the logs.
